mgcs_v3/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from mysite.forms import MyLoginForm, MyPasswordChangeForm
from mysite.views import HomeView
from mysite.views import UserCreateView, ProfileUpdateView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')),
    path('account/register/', UserCreateView.as_view(), name='register'),
    path('account/login/', auth_views.login,
        {'authentication_form': MyLoginForm,
         'template_name': 'registration/login.html',
         'redirect_field_name': 'home'}, name='login'),
    path('account/password_change/', auth_views.password_change,
        {'post_change_redirect' :'/',
         'password_change_form': MyPasswordChangeForm }, name='password_change'),
    path('account/profile/<pk>[0-9]/edit/', ProfileUpdateView.as_view(), name='edit_profile'),


    path('openstack/', include('openstack_driver.urls', namespace='openstack')),
]

openstack_driver/urls.py
from django.conf.urls import url
from django.urls import include, path
from openstack_driver import views
from openstack_driver.views import InstanceView, ComputeView, ImageView, NetworkView, MeteringView, StorageView, \
    TopologyView, RouterView, HypervisorView

app_name = 'openstack'
urlpatterns = [
    path('hypervisor/', HypervisorView.as_view(), name='admin_hypervisor'),

    path('make_instance/', InstanceView.as_view(), name='make_instance'),
    path('instances/', ComputeView.as_view(), name='instances'),
    path('image/', ImageView.as_view(), name='image'),
    path('storage/', StorageView.as_view(), name='storage'),

    path('network/', NetworkView.as_view(), name='network'),
    path('topology/', TopologyView.as_view(), name='topology'),
    path('router/', RouterView.as_view(), name='router'),

    path('metering/', MeteringView.as_view(), name='metering'),


    path('rest/v2/images/', views.image, name='rest_images'),
    path('rest/v2/networks/', views.network, name='rest_networks'),
    path('rest/servers/', views.server, name='rest_servers'),
    path('rest/server_detail/', views.server_detail, name='rest_server_detail'),
    path('rest/flavors/detail/', views.flavor, name='rest_flavors'),
    path('rest/zones/', views.zone, name='rest_zones'),
    path('rest/v1/hypervisors/', views.hypervisor, name='restapi_hypervisor'),
    path('rest/v2/meters/', views.meter, name='rest_meters'),
    path('rest/resources/', views.resource, name='rest_resource'),
]

templates/auth_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>MGCS</title><meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" href="{% static "css/bootstrap.min.css"%}" />
    <link rel="stylesheet" href="{% static "css/bootstrap-responsive.min.css"%}" />
    <link rel="stylesheet" href="{% static "css/matrix-login.css"%}" />
    <link rel="stylesheet" href="{% static "font-awesome/css/font-awesome.css"%}" />
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800' rel='stylesheet' type='text/css'>
</head>
<body>

{% block content %}{% endblock %}

<script src={% static "js/jquery.min.js" %}></script>
<script src={% static "js/matrix.login.js" %}></script>

</body>

</html>

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>MGCS</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" href="{% static "css/bootstrap.min.css"%}" />
    <link rel="stylesheet" href="{% static "css/bootstrap-responsive.min.css"%}" />
    <link rel="stylesheet" href="{% static "css/fullcalendar.css"%}" />
    <link rel="stylesheet" href="{% static "css/matrix-style.css"%}" />
    <link rel="stylesheet" href="{% static "css/matrix-media.css"%}" />
    <link rel="stylesheet" href="{% static "font-awesome/css/font-awesome.css"%}" />
    <link rel="stylesheet" href="{% static "css/jquery.gritter.css"%}" />
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800' rel='stylesheet' type='text/css'>

    {% block stylesheet %}{% endblock %}

    <style></style>
</head>

<body>

<!--Header-part-->
<div id="header">
    <h1><a href="{% url "home" %}">MGCS</a></h1>

</div>
<!--close-Header-part-->

<!--top-Header-menu-->
<div id="user-nav" class="navbar navbar-inverse ">
    <ul class="nav navbar-nav navbar-right">
        <li  class="dropdown" id="profile-messages" ><a title="" href="#" data-toggle="dropdown" data-target="#profile-messages" class="dropdown-toggle"><i class="icon icon-user"></i>  <span class="text">Welcome! {{ user.first_name }}</span><b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><a href="/account/profile/{{ user.pk }}/edit/"><i class="icon-user"></i> My Profile</a></li>
                <li class="divider"></li>
                <li><a href="{% url 'password_change' %}"><i class="icon-key"></i> Change Password</a></li>
                <li class="divider"></li>
                <li><a href="{% url "logout" %}"><i class="icon-unlock"></i> Log Out</a></li>
            </ul>
        </li>
    </ul>
</div>
<!--close-top-Header-menu-->
<!--sidebar-menu-->
<div id="sidebar"><a href="#" class="visible-phone"><i class="icon icon-home"></i>Dashboard</a>
    <ul>
        <li id="home_tap" class="active"><a href="{% url "home" %}"><i class="icon icon-home"></i><span>Home</span></a></li>
        {% if user.username == 'admin' %}
            <li id="admin_tap" class="submenu"><a href="#"><i class="icon icon-user"></i><span>Admin</span> <span class="label label-important">1</span></a>
                <ul>
                    <li id="admin_hypervisor_tap"><a href="{% url "openstack:admin_hypervisor" %}">Hypervisors</a></li>
                </ul>
            </li>
        {% endif %}
        <li id="compute_tap" class="submenu"> <a href="#"><i class="icon icon-th-list"></i><span>Compute</span> <span class="label label-important">4</span></a>
            <ul>
                <li id="make_instance_tap"><a href="{% url "openstack:make_instance" %}">Launch Instance</a></li>
                <li id="instances_tap"><a href="{% url "openstack:instances" %}">Instances</a></li>
                <li id="image_tap"><a href="{% url "openstack:image" %}">Image</a></li>
                <li id="storage_tap"><a href="{% url "openstack:storage" %}">Storage</a></li>
            </ul>
        </li>
        <li id="network_tap" class="submenu"> <a href="#"><i class="icon icon-sitemap"></i><span>Network</span> <span class="label label-important">3</span></a>
            <ul>
                <li id="topology_tap"><a href="{% url "openstack:topology" %}">Topology</a></li>
                <li id="network_detail_tap"><a href="{% url "openstack:network" %}">Network</a></li>
                <li id="router_tap"><a href="{% url "openstack:router" %}">Router</a></li>
            </ul>
        </li>
        <li id="metering_tap" class=""><a href="{% url "openstack:metering" %}"><i class="icon icon-signal"></i><span>Metering</span></a></li>
    </ul>
</div>
<!--sidebar-menu-->

{% block content %}{% endblock %}

<!--Footer-part-->
<div class="row-fluid">
    <div id="footer" class="span12"> 2013 &copy; Matrix Admin. Brought to you by <a href="http://themedesigner.in">Themedesigner.in</a> </div>
</div>
<!--end-Footer-part-->

<script src={% static "js/excanvas.min.js" %}></script>
<script src={% static "js/jquery.min.js" %}></script>
<script src={% static "js/jquery.ui.custom.js" %}></script>
<script src={% static "js/bootstrap.min.js" %}></script>
<script src={% static "js/jquery.flot.min.js" %}></script>
<script src={% static "js/jquery.flot.resize.min.js" %}></script>
<script src={% static "js/jquery.peity.min.js" %}></script>
<script src={% static "js/fullcalendar.min.js" %}></script>
<script src={% static "js/matrix.js" %}></script>
<script src={% static "js/matrix.dashboard.js" %}></script>
<script src={% static "js/jquery.gritter.min.js" %}></script>
<script src={% static "js/matrix.interface.js" %}></script>
<script src={% static "js/matrix.chat.js" %}></script>
<script src={% static "js/jquery.validate.js" %}></script>
<script src={% static "js/matrix.form_validation.js" %}></script>
<script src={% static "js/jquery.wizard.js" %}></script>
<script src={% static "js/jquery.uniform.js" %}></script>
<script src={% static "js/select2.min.js" %}></script>
<script src={% static "js/matrix.popover.js" %}></script>
<script src={% static "js/jquery.dataTables.min.js" %}></script>
<script src={% static "js/matrix.tables.js" %}></script>


{% block script %}{% endblock %}

</body>
</html>

templates/home.html
{% extends "base.html" %}ㅑ
{% load staticfiles %}

{% block content %}
    <!--main-container-part-->
    <div id="content">
        <!--breadcrumbs-->
        <div id="content-header">
            <div id="breadcrumb">
                <a href="{% url "home" %}" title="Go to Home" class="tip-bottom"><i class="icon-home"></i> Home</a></div>
            <h1>내 자원 현황</h1>
            <!--이곳에 내용을 입력하세요-->
        </div>
        <div class="container-fluid">
            <hr>
            <div class="row-fluid">
                <div class="span3">
                    <div class="widget-box">
                        <div class="widget-title"> <span class="icon"> <i class="icon-list"></i> </span>
                            <h5>Instances</h5>
                        </div>
                        <div class="widget-content">
                            <div id="instance_chart" style="min-width: 200px; height: 200px; max-width: 600px; margin: 0 auto"></div>
                        </div>
                    </div>
                </div>

                <div class="span3">
                    <div class="widget-box">
                        <div class="widget-title"> <span class="icon"> <i class="icon-list"></i> </span>
                            <h5>vCPUs</h5>
                        </div>
                        <div class="widget-content">
                            <div id="cpu_chart" style="min-width: 200px; height: 200px; max-width: 600px; margin: 0 auto"></div>
                        </div>
                    </div>
                </div>

                <div class="span3">
                    <div class="widget-box">
                        <div class="widget-title"> <span class="icon"> <i class="icon-list"></i> </span>
                            <h5>RAM</h5>
                        </div>
                        <div class="widget-content">
                            <div id="ram_chart" style="min-width: 200px; height: 200px; max-width: 600px; margin: 0 auto"></div>
                        </div>
                    </div>
                </div>

                <div class="span3">
                    <div class="widget-box">
                        <div class="widget-title"> <span class="icon"> <i class="icon-list"></i> </span>
                            <h5>Floating IP</h5>
                        </div>
                        <div class="widget-content">
                            <div id="f_ip_chart" style="min-width: 200px; height: 200px; max-width: 600px; margin: 0 auto"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="widget-box">
                <div class="widget-title"> <span class="icon"> <i class="icon-th"></i> </span>
                    <h5>내 인스턴스</h5>
                </div>
                <div class="widget-content">
                    <table id="instance_table"  class="table table-bordered table-striped with-check">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>인스턴스 이름</th>
                            <th>이미지 이름</th>
                            <th>vCPUs</th>
                            <th>RAM</th>
                            <th>Disk</th>
                            <th>전원상태</th>
                            <th>생성시간</th>
                        </tr>
                        </thead>
                        <tbody>

                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>
{% endblock content %}

{% block script %}

    <script src="{% static "chart/highcharts.js" %}"></script>
    <script src="{% static "chart/exporting.js" %}"></script>

    <script>
        $.get("/openstack/rest/resources", function(data){
            var total_vm = data.resources.maxTotalInstances;
            var used_vm = data.resources.totalInstancesUsed;
            var free_vm = total_vm - used_vm;

            var total_cpu = data.resources.maxTotalCores;
            var used_cpu = data.resources.totalCoresUsed;
            var free_cpu = total_cpu - used_cpu;

            var total_ram = data.resources.maxTotalRAMSize;
            var used_ram = data.resources.totalRAMUsed;
            var free_ram = total_ram - used_ram;

            var total_f_ip = data.resources.maxTotalFloatingIps;
            var used_f_ip = data.resources.totalFloatingIpsUsed;
            var free_f_ip = total_f_ip - used_f_ip;

            Highcharts.chart('instance_chart', {
                chart: {
                    plotBackgroundColor: '#f9f9f9',
                    plotBorderWidth: 0,
                    plotShadow: false
                },
                title: {
                    text: total_vm+'개 에서 '+used_vm+'개 사용됨, '+free_vm+'개 남음',
                    align: 'center',
                    verticalAlign: 'middle',
                    style: {
                        fontSize: '13px'
                    },
                    y: 100
                },
                plotOptions: {
                    pie: {
                        dataLabels: {
                            enabled: true,
                            distance: -34,
                            style: {
                                fontWeight: '',
                                color: 'white'
                            }
                        },
                        center: ['50%', '50%']
                    }
                },
                series: [{
                    type: 'pie',
                    name: 'Volumes',
                    data: [
                        ['Free VMs', free_vm],
                        ['Used VMs', used_vm]
                    ]
                }]
            });

            Highcharts.chart('cpu_chart', {
                chart: {
                    plotBackgroundColor: '#f9f9f9',
                    plotBorderWidth: 0,
                    plotShadow: false
                },
                title: {
                    text: total_cpu+'개 에서 '+used_cpu+'개 사용됨, '+free_cpu+'개 남음',
                    align: 'center',
                    verticalAlign: 'middle',
                    style: {
                        fontSize: '13px'
                    },
                    y: 100
                },
                plotOptions: {
                    pie: {
                        dataLabels: {
                            enabled: true,
                            distance: -34,
                            style: {
                                fontWeight: '',
                                color: 'white'
                            }
                        },
                        center: ['50%', '50%']
                    }
                },
                series: [{
                    type: 'pie',
                    name: 'Volumes',
                    data: [
                        ['Free vCPUs', free_cpu],
                        ['Used vCPUs', used_cpu]
                    ]
                }]
            });

            Highcharts.chart('ram_chart', {
                chart: {
                    plotBackgroundColor: '#f9f9f9',
                    plotBorderWidth: 0,
                    plotShadow: false
                },
                title: {
                    text: (total_ram/1024).toFixed(0)+'GB 에서 '+(used_ram/1024).toFixed(0)+'GB 사용됨, '+(free_ram/1024).toFixed(0)+'GB 남음',
                    align: 'center',
                    verticalAlign: 'middle',
                    style: {
                        fontSize: '13px'
                    },
                    y: 100
                },
                plotOptions: {
                    pie: {
                        dataLabels: {
                            enabled: true,
                            distance: -34,
                            style: {
                                fontWeight: '',
                                color: 'white'
                            }
                        },
                        center: ['50%', '50%']
                    }
                },
                series: [{
                    type: 'pie',
                    name: 'Volumes',
                    data: [
                        ['Free RAM', free_ram],
                        ['Used RAM', used_ram]
                    ]
                }]
            });

            Highcharts.chart('f_ip_chart', {
                chart: {
                    plotBackgroundColor: '#f9f9f9',
                    plotBorderWidth: 0,
                    plotShadow: false
                },
                title: {
                    text: total_f_ip+'개 에서 '+used_f_ip+'개 사용됨, '+free_f_ip+'개 남음',
                    align: 'center',
                    verticalAlign: 'middle',
                    style: {
                        fontSize: '13px'
                    },
                    y: 100
                },
                plotOptions: {
                    pie: {
                        dataLabels: {
                            enabled: true,
                            distance: -34,
                            style: {
                                fontWeight: '',
                                color: 'white'
                            }
                        },
                        center: ['50%', '50%']
                    }
                },
                series: [{
                    type: 'pie',
                    name: 'Volumes',
                    data: [
                        ['Free Floating IP', free_f_ip],
                        ['Used Floating IP', used_f_ip]
                    ]
                }]
            });

            $("rect.highcharts-background").attr('fill','#f9f9f9');
            $("rect.highcharts-button-box").attr('fill','#f9f9f9');

            $.get("/openstack/rest/server_detail", function(data) {
                for (var i = 0; i < data.server_details.length; i++) {
                    $('#instance_table').append(
                        "<tr>" +
                        "<td>" + Number(i+1) + "</td>" +
                        "<td>" + data.server_details[i].name + "</td>" +
                        "<td>" + data.server_details[i].image + "</td>" +
                        "<td>" + data.server_details[i].flavor_cpu + "</td>" +
                        "<td>" + (data.server_details[i].flavor_ram/1024).toFixed(0) + " GB" + "</td>" +
                        "<td>" + data.server_details[i].flavor_disk + " GB" + "</td>" +
                        "<td>" + data.server_details[i].power + "</td>" +
                        "<td>" + data.server_details[i].created + "</td>" +
                        "</tr>"
                    )
                }
            });
        });
    </script>
{% endblock %}